paths:
    type: dict
    required: true
    contains_any_of: [input, root, previous_iterations, current_iterations ]
    schema:
        gmxrc:
            type: string
            required: true
        scoring_functions:
            type: string
            required: true
        mdp:
            type: string
            required: true
        input:
            type: list
            minlength: 1
            maxlength: 12
            schema:
                type: string
            required: false
            excludes: [previous_iterations, current_iterations]
            dependencies: root 
        root:
            type: string
            required: false
            excludes: [previous_iterations, current_iterations]
            dependencies: input
        previous_iterations:
            type: list
            minlength: 1
            maxlength: 12
            required: false
            schema:
                type: string
            excludes: [input, root]
            dependencies: current_iterations
        current_iterations:
            type: list
            minlength: 1
            maxlength: 12
            required: false
            schema:
                type: string
            excludes: [input, root]
main:
    type: dict
    required: true
    schema:
        name:
            type: string
            required: true
        mode:
            type: string
            required: true
            default: "protocol"
            allowed: ["protocol", "run", "run_npt", "score"]
        prefix:
            type: string
            required: false
            default: "npt_"
        epochs:
            type: integer
            default: 0
            required: false
            min: 0
            max: 48
        branches:
            type: integer
            default: 0
            required: false
            min: 0
            max: 24
        prune:
            type: integer
            default: 1
            required: false
            min: 1
            max: 4

md:
    type: dict
    required: true
    schema:
        gmx_bin:
            type: string
            required: false
            default: "gmx"
        mdp_names:
            type: dict
            required: true
            schema:
                min_water_mdp:
                    type: string
                    default: min_water.mdp
                min_environment_mdp:
                    type: string
                    default: min_environment.mdp
                min_mdp:
                    type: string
                    default: min.mdp
                nvt_mdp:
                    type: string
                    default: nvt.mdp
                npt_mdp:
                    type: string
                    default: npt.mdp
        ngpus:
            type: integer
            min: 1
            max: 12
            default: 0
        mpi_procs:
            type: integer
            min: 1
            max: 48
            default: 1
        omp_procs:
            type: integer
            min: 1
            max: 48
            default: 1
        force_field:
            type: string
            allowed: [amber03, amber94, amber96, amber99, amber99sb-ildn,
                        amber99sb, amberGS, charmm27, gromos43a1, gromos43a2,
                        gromos45a3, gromos53a5, gromos53a6, gromos54a7, oplsaa]
            default: "amber99sb-ildn"
            required: false
        water_type:
            type: string
            default: "tip3p"
            required: false
            allowed: [tip3p, tip4p, tip4pew, tip5p, spc, spce]

target:
    type: dict
    required: true
    schema:
        chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string

binder:
    type: dict
    required: true
    schema:
        chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string
                allowed: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]
                required: true
        mutating_chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string
                allowed: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]
                required: true
        mutating_resSeq:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: list
                minlength: 1
                maxlength: 20
                required: true
                schema:
                    type: integer
                    min: 1
                    max: 999999
                    required: true

scoring:
    type: dict
    required: true
    schema:
        functions:
            type: list
            minlength: 1
            maxlength: 20
            required: true
            schema:
                type: string
                allowed: [bach, bluues, evoef2, haddock, pisa, rosetta, zrank, irad, firedock]
        consensus_threshold:
            type: integer
            min: 1
            max: 20
            required: true
        nprocs:
            type: integer
            min: 1
            max: 256
            default: 0

