paths:
    type: dict
    required: true
    contains_any_of: [input, work ]
    schema:
        gmxrc:
            type: string
            required: true
            is_directory: true
        scoring_functions:
            type: string
            required: true
            is_directory: true
        mutator:
            type: string
            required: true
            is_directory: true
        mdp:
            type: string
            required: true
            is_directory: true
        input:
            type: list
            minlength: 1
            maxlength: 12
            schema:
                type: string
                is_directory: true
            required: false
        work:
            type: string
            required: true
        tleap:
            type: string
            required: false
            is_directory: true

main:
    type: dict
    required: true
    schema:
        name:
            type: string
            required: true
        mode:
            type: string
            required: true
            default: "evolve"
            allowed: ["evolve", "run", "run_npt", "score"]
        prefix:
            type: string
            required: false
            default: "npt_"
protocol:
    type: dict
    required: false
    schema:
        epochs:
            type: integer
            default: 0
            min: 0
            max: 48
        branches:
            type: integer
            default: 1
            min: 1
            max: 24
        prevent_fewer_branches:
            type: boolean
            default: true
        prune:
            type: integer
            required: false
            min: 1
            max: 4
        prunner:
            type: string
            default: "adaptive"
            required: false
            allowed: ["top", "adaptive", "threshold"]
            warn_overrides: prune
        generator:
            type: string 
            default: "SPM_4"
            required: false
            crosscheck: [branches] 
            allowed: ["SPM_4", "SPM_R&B"]
        mutator:
            type: string
            default: "evoef2"
            allowed: ["evoef2", "biobb"]
        memory_size:
            type: integer
            required: false
            min: 0
            max: 12
            higher_than_length_of: memory_positions
        memory_positions:
            type: list
            required: false
            dependencies: memory_size
            minlength: 1
            maxlength: 12
            schema:
                type: list
                minlength: 1
                maxlength: 36
                schema:
                    type: integer
                    min: 1
                    max: 99999
        failed_memory_size:
            type: integer
            required: false
            min: 0
            max: 12
            higher_than_length_of: memory_positions
            higher_than_length_of: failed_memory_positions
        failed_memory_positions:
            type: list
            required: false
            dependencies: memory_size
            minlength: 1
            maxlength: 12
            schema:
                type: list
                minlength: 1
                maxlength: 36
                schema:
                    type: integer
                    min: 1
                    max: 99999

        memory_aminoacids:
            type: list
            required: false
            minlength: 1
            maxlength: 12
            schema:
                type: list
                minlength: 1
                maxlength: 36
                schema:
                    type: string
                    allowed: ['A', 'R', 'N', 'D', 'C', 'E', 'Q', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
                    minlength: 1
                    maxlength: 1
md:
    type: dict
    required: true
    schema:
        gmx_bin:
            type: string
            required: false
            default: "gmx"
        mdp_names:
            type: dict
            required: true
            schema:
                min_mdp:
                    type: string
                    default: "min.mdp"
                nvt_mdp:
                    type: string
                    default: "nvt.mdp"
                npt_mdp:
                    type: string
                    default: "npt.mdp"
        ngpus:
            type: integer
            min: 1
            max: 12
            required: true
            warn_thread_availability: [mpi_procs, omp_procs]
            same_as_length_of: pinoffsets
        mpi_procs:
            type: integer
            min: 1
            max: 48
            default: 1
        omp_procs:
            type: integer
            min: 1
            max: 48
            default: 1
        pinoffsets:
            type: list
            minlength: 1
            maxlength: 12
            required: true
            schema:
                type: integer
        use_tleap:
            type: boolean
            default: false
        force_field:
            type: string
            allowed: ["amber03", "amber94", "amber96", "amber99", "amber99sb-ildn",
                        "amber99sb", "amberGS", "charmm27", "gromos43a1", "gromos43a2",
                        "gromos45a3", "gromos53a5", "gromos53a6", "gromos54a7", "oplsaa"]
            default: "amber99sb-ildn"
            required: false
        water_type:
            type: string
            default: "tip3p"
            required: false
            allowed: ["tip3p", "tip4p", "tip4pew", "tip5p", "spc", "spce"]
        use_box:
            type: boolean
            required: true
            default: false
            check_with: box_check
        box_type:
            type: string
            required: false
            allowed: ["triclinic", "cubic", "dodecahedron", "octahedron"]
        dist_to_box:
            type: float 
            required: false
            min: 0.5
            max: 9.0
        box:
            type: list
            required: false
            minlength: 3
            maxlength: 3
            schema:
                type: float
target:
    type: dict
    required: true
    schema:
        chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string
                maxlength: 1

binder:
    type: dict
    required: true
    schema:
        chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string
                allowed: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]
                required: true
        mutating_chainID:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            schema:
                type: string
                allowed: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]
                required: true
        mutating_resSeq:
            type: list
            minlength: 1
            maxlength: 10
            required: true
            same_length: mutating_chainID
            schema:
                type: list
                minlength: 1
                maxlength: 20
                required: true
                sorted: true
                unique: true
                schema:
                    type: integer
                    min: 1
                    max: 99999
                    required: true

scoring:
    type: dict
    required: true
    schema:
        functions:
            type: list
            minlength: 1
            maxlength: 20
            required: true
            schema:
                type: string
                allowed: ["bach", "bluues", "evoef2", "haddock", "pisa", "rosetta", "zrank", "irad", "firedock"]
        consensus_threshold:
            type: integer
            min: 1
            max: 20
            required: true
            lower_than_length_of: functions
        nprocs:
            type: integer
            min: 1
            max: 256
            required: true
            warn_when_above: 64

