name: locuaz
channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.9.15,<=3.10.10
  - conda-forge::scipy
  - conda-forge::ipykernel
  - conda-forge::jupyterlab
  - conda-forge::attrs
  - conda-forge::networkx
  - conda-forge::pygraphviz
  - conda-forge::ambertools
  - conda-forge::mpi4py=3.1.3
  - conda-forge::compilers=1.2.0
  - conda-forge::parmed==4.0.0
  - conda-forge::openbabel
  - conda-forge::tensorflow
  - pip
  - pip:
    - black
    - mypy
    - mypy_extensions
    - pytest
    - flake8
    - sphinx
    - sphinx-rtd-theme
    - pyyaml
    - types-pyyaml
    - cerberus
    - chemfiles
    - mdanalysis
    - biobb_gromacs==4.0.0
    - biobb_common==4.0.0
    - biobb_analysis==4.0.0
    - biobb_model==4.0.0
    - biobb_common==4.0.0
    - biobb_io==4.0.0                  
    - pdb2pqr
    - gmx-mmpbsa
    - tqdm
    - freesasa
    - py
