{% set name = "locuaz" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/locuaz-{{ version }}.tar.gz
  sha256: 423e7cdfe58dde46751f605eb88da38dc449ec070fb202a647ea2ab33cce6ed4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.10,<3.11
    - scipy
    - numpy >=1.21.0,<2.0.0
    - openbabel
    - ambertools>=22.0.0
    - tensorflow
    - mdanalysis>=2.3.0
    - bioconda::biobb_common==4.0.0
    - bioconda::biobb_analysis==4.0.0
    - bioconda::biobb_model==4.0.0
    - bioconda::biobb_io==4.0.0
    - bioconda::biobb_gromacs==4.0.0
    - pdb2pqr
    - tqdm
    - pytest
    - sphinx
    - sphinx-rtd-theme
    - cerberus
    - attrs
    - networkx
    - pygraphviz

test:
  imports:
    - locuaz
    - locuaz.DLPacker
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Antibody optimization protocol
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Patricio
