{% set name = "locuaz" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/locuaz-{{ version }}.tar.gz
  sha256: 2c7c18a9925eae67fb756cdcb78910f862a9dc028bb25549acc54bd9d8dcbb4a

build:
  noarch: True
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.11
    - setuptools >=42
    - wheel
    - pip
  run:
    - condaforge::python >=3.9,<3.11
    - condaforge::scipy
    - condaforge::numpy >=1.21.0,<2.0.0
    - condaforge::mmcif_pdbx>=1.1.2,<=2.0.0
    - condaforge::ambertools>=22.0.0
    - condaforge::tensorflow
    - condaforge::mdanalysis>=2.3.0
    - condaforge::chemfiles
    - condaforge::freesasa
    - condaforge::gmx_mmpbsa
    - condaforge::py
    - condaforge::docutils<0.18
    - condaforge::pdb2pqr
    - condaforge::openbabel
    - condaforge::tqdm
    - condaforge::pytest
    - condaforge::sphinx
    - condaforge::sphinx-rtd-theme
    - condaforge::cerberus
    - condaforge::attrs
    - condaforge::networkx
    - condaforge::pygraphviz
    - bioconda::biobb_common==4.0.0
    - bioconda::biobb_analysis==4.0.0
    - bioconda::biobb_model==4.0.0
    - bioconda::biobb_io==4.0.0
    - bioconda::biobb_gromacs==4.0.0

test:
  imports:
    - locuaz
    - locuaz.DLPacker
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Antibody optimization protocol
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Patricio
